### ISSUE TITLE
⚠️ quantum-cli has degraded performance

### ISSUE THREAD

**Issue by pnhosta** [hostwithquantum/status.planetary-quantum.com#12]
In [`c5e0aa9`](https://github.com/hostwithquantum/status.planetary-quantum.com/commit/c5e0aa928e947139add7d3c7123a98f17e3b4380
), quantum-cli (https://cli.planetary-quantum.com/) experienced **degraded performance**:
- HTTP code: 200
- Response time: 3884 ms

**Comment by pnhosta** [comment]
**Resolved:** quantum-cli performance has improved in [`2a9d33e`](https://github.com/hostwithquantum/status.planetary-quantum.com/commit/2a9d33ec499eb1aff3facf25e3c63cdc51030afe
).

**Comment by till** [comment]
Looks like Github Pages was degraded. Couldn't find an incident though.
